CREATE SEQUENCE IF NOT EXISTS product_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE product
(
    id       INTEGER NOT NULL,
    name     VARCHAR(255),
    price    INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);